//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Comessa6.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class citemcount
    {
        public int id { get; set; }
        public Nullable<int> itemId { get; set; }
        public int count { get; set; }
    
        public virtual citem citem { get; set; }
    }
}
