//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Comessa6.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class citem
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public citem()
        {
            this.corder = new HashSet<corder>();
            this.citemcount = new HashSet<citemcount>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public string keywords { get; set; }
        public decimal price { get; set; }
        public Nullable<int> providerId { get; set; }
        public bool isVisible { get; set; }
        public byte[] image { get; set; }
        public int priority { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<corder> corder { get; set; }
        public virtual cprovider cprovider { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<citemcount> citemcount { get; set; }
    }
}
