//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Comessa6.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class cnotification
    {
        public int id { get; set; }
        public int userId { get; set; }
        public Nullable<int> senderId { get; set; }
        public System.DateTime date { get; set; }
        public string text { get; set; }
        public string eventCode { get; set; }
    
        public virtual cuser cuser { get; set; }
        public virtual cuser cuser1 { get; set; }
    }
}
