//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Comessa6.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Comessa5Context : DbContext
    {
        public Comessa5Context()
            : base("name=comessa5Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<citem> citem { get; set; }
        public virtual DbSet<cnotification> cnotification { get; set; }
        public virtual DbSet<corder> corder { get; set; }
        public virtual DbSet<cpayment> cpayment { get; set; }
        public virtual DbSet<cprovider> cprovider { get; set; }
        public virtual DbSet<cuser> cuser { get; set; }
        public virtual DbSet<citemcount> citemcount { get; set; }
        public virtual DbSet<vorders> vorders { get; set; }
        public virtual DbSet<vpayment> vpayment { get; set; }
    }
}
