//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Comessa6.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class cpayment
    {
        public int id { get; set; }
        public string comment { get; set; }
        public Nullable<int> type { get; set; }
        public Nullable<int> senderId { get; set; }
        public Nullable<int> recipientId { get; set; }
        public decimal amount { get; set; }
        public System.DateTime date { get; set; }
    
        public virtual cuser cuser { get; set; }
    }
}
