//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Comessa6.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vorders
    {
        public int id { get; set; }
        public string itemName { get; set; }
        public string comment { get; set; }
        public decimal quantity { get; set; }
        public decimal price { get; set; }
        public decimal total { get; set; }
        public string ordering { get; set; }
        public Nullable<int> status { get; set; }
        public System.DateTime date { get; set; }
    }
}
